### ISSUE TITLE
Preroll 2 Ads Diagram is misleading on startup time measurement

### ISSUE THREAD

**Issue by heff** [cta-wave/R4WG20-QoE-Metrics#2]
In the diagram it lists "startup time" twice before the first ad, but the definition of initial startup time includes all of the time up to the playback of the first ad.

We should change this to only say "startup time" once. Possibly change to "initial startup time" to be even more clear.

![image](https://user-images.githubusercontent.com/166/53763198-1af92f00-3e98-11e9-9853-d38a3dac4513.png)

**Comment by wilaw** [comment]
Moved to https://github.com/cta-standards/R4WG20-QoE-Metrics/issues/30
