### ISSUE TITLE
Provide PR-able version of the spec

### ISSUE THREAD

**Issue by heff** [cta-wave/R4WG20-QoE-Metrics#3]
A request from FOMS (incl. @cpillsbury) was to add a markdown version of the spec for PRs. It allow conversations over diffs.

@wilaw suggested using the [bikeshed markdown version](https://tabatkins.github.io/bikeshed/#markdown) in case we want to compile it at some point.

Though to be clear, we're still figuring out how updates to the repo will make their way into the official doc of the R4WG20 group. It will likely be talking through the diff between the original version and updates to this repo.

**Comment by wilaw** [comment]
Moved to https://github.com/cta-standards/R4WG20-QoE-Metrics/issues/29
