### ISSUE TITLE
Create Media Info API example for bitrate metrics

### ISSUE THREAD

**Issue by heff** [cta-wave/R4WG20-QoE-Metrics#4]
This spec requires access to the currently playing bitrate, to calculate _bitsPlayed_. This isn't easy to get on the web currently. One of the requests at FOMS was something like a Media Info API (similar in concept to the Media Capabilities API) that could provide those details. A request from browser developers was an example of what we would want to see from this API.

So we should create an example of what we think the API could look like. The action item included @robwalch. 

A few suggestions from Eric Carlson and others at apple:

* Check out WebRTC Stats API for an example of similar stats already made available by the browser.
* Look to the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) as a better example of an API where you tell the browser what details you want. Otherwise the browser has to dig into the system to get all the info each time which is costly.
* Look at AV Player HLS stats for example of what people have asked for from that API.

**Comment by heff** [comment]
There was also discussion around access to Frame Rate/Frames Played, and I think we could wrap that conversation in here until we determine we need a separate issue for it.

**Comment by wilaw** [comment]
Moved to https://github.com/cta-standards/R4WG20-QoE-Metrics/issues/28
