### ISSUE TITLE
Create a reference table for Event matches on different platforms

### ISSUE THREAD

**Issue by heff** [cta-wave/R4WG20-QoE-Metrics#5]
At FOMS @cpillsbury mentioned it would be great to map events on different platforms (e.g. html5, iOS AVPlayer, ExoPlayer) to the events listed in this spec. This would help clarify the intention behind the events, unify implementations, and be a first step towards a reference implementation. 

The process would have the added benefit of verifying what's possible on different platforms and finding any challenges.

**Comment by wilaw** [comment]
MOved to https://github.com/cta-standards/R4WG20-QoE-Metrics/issues/27
