### ISSUE TITLE
Weird PDF formatting

### ISSUE THREAD

**Issue by ghost** [cta-wave/R4WG20-QoE-Metrics#6]
There seems to be some data formatting issues in the columns. making the left column with the term names unreadable (pages 5-6).

(I opened in several PDF readers: Adobe, Chrome browser, Mac Preview.  All have same issue)

**Comment by heff** [comment]
We've moved the discussion over to a new repo (with better formatting I think)

https://github.com/cta-standards/R4WG20-QoE-Metrics/issues
