### ISSUE TITLE
Feedback from the DASH Industry Forum

### ISSUE THREAD

**Issue by wilaw** [cta-wave/R4WG20-QoE-Metrics#8]
Feedback based on a review call 4/1/19 - present Will, Andy, Nicol, Zack.

1. Document should note that in multi-threaded environments (native players for example), there is the possibility of events being received in a different order to that in which they were dispatched. This difference may only be a millisecond or two, but it would be sufficient to confuse an analytics app following a rigid interpretation of the event sequence. It is suggested that analytics implementations maintain an play state model in order to correctly interpret event sequences. 
2. For Nielson C-window stitched content, a note should be made that players must synthesize the appropriate events, as there will not be an obvious discontinuity in the content to signal such a transition.
3. Add a note to the table entry for playerResize event that this refers to the displayed area of the player and not the decoded are of the video. 
4. Add a note to the table entry for EncodedVideoWidth/Height explaining that this refers to the width and height reported by the decoder, which may not match what was reported in the manifest. We would consider the decoder the source of truth. IN the event that the decoder infomation is not available within the player, then the reported video dimensions from the manifest may be used. 

Reported by Will

**Comment by heff** [comment]
Moved to a new repo:
https://github.com/cta-standards/R4WG20-QoE-Metrics/issues/25
